accepted = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "Zlib",
  "CDLA-Permissive-2.0",
]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false

[ring]
accepted = ["OpenSSL"]
